# pas reussi a faire marcher ça donc j'autorise tout pour le moment
#cors:
#  allowed-origins:
#    - "http://localhost:8080"
#    - "http://localhost:8081"
#    - "http://localhost:8083"

spring:
  application:
    name: auth
  data:
    mongodb:
      host: mongo-auth
      port: 27017
      username: admin
      password: passadmin
      authentication-database: admin
      database: authdb
      auto-index-creation: true
  profiles:
    active: docker

auth:
  token:
    secret: ${AUTH_TOKEN_AES256_KEY}
